git config --global alias.gs 'git status '
git config --global alias.gss 'git status -s'
git config --global alias.gp 'git pull'
git config --global alias.gpo 'git pull origin '
git config --global alias.gh 'git push'
git config --global alias.gho 'git push origin '
git config --global alias.ga 'git add '
git config --global alias.gaa 'git add -A'
git config --global alias.gb 'git branch '
git config --global alias.gc 'git commit '
git config --global alias.gcm 'git commit -m '
git config --global alias.gd 'git diff'
git config --global alias.go 'git checkout '
git config --global alias.gob 'git checkout -b'
git config --global alias.got 'git '
git config --global alias.get 'git '
git config --global alias.g 'git '
git config --global alias.gm 'git merge '
git config --global alias.gr 'git reset '
git config --global alias.gdf 'git clean -f'
git config --global alias.gt 'git stash '
git config --global alias.gtp 'git stash pop'